/**
 * Pipeline statuses:
 * RECEIVED -> REVIEWING -> GENERATING -> VALIDATING -> RELEASED
 * Terminal rejection path: REJECTED
 * Terminal failure path: FAILED
 */
const PIPELINE_STATUS = {
  RECEIVED: 'RECEIVED',
  REVIEWING: 'REVIEWING',
  GENERATING: 'GENERATING',
  VALIDATING: 'VALIDATING',
  RELEASED: 'RELEASED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED'
};

const TERMINAL_STATUS = new Set([
  PIPELINE_STATUS.RELEASED,
  PIPELINE_STATUS.REJECTED,
  PIPELINE_STATUS.FAILED
]);

module.exports = {
  PIPELINE_STATUS,
  TERMINAL_STATUS
};
